name: agenda
version: 0.6.16-1
author: Igor Demyanov <igor.demyanov@gmail.com>
description: "Port agenda js 0.6.16 \nLight weight job scheduler for Dart"
homepage: https://github.com/DisDis/agenda_dart
environment:
  sdk: '>=1.3.0'
dependencies:
  mongo_dart: '>=0.1.42 <0.2.0'
